apiVersion: batch/v1
kind: Job
metadata:
  name: node-app-job
spec:
  completions: 7
  parallelism: 5
  template:
    spec:
      containers:
      - name: node-app-job
        image: alpine
        command: ["echo", "Welcome to my Node app"]
      restartPolicy: Never